name: Build .NET WinForms Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8.1'  # Or the version of .NET Framework you want to target

    - name: Restore NuGet packages
      run: nuget restore Optimade.sln

    - name: Build
      run: msbuild /p:Configuration=Release Optimade.sln
